sudo: required

matrix:
  include:
    - os: linux
	  addons:
	    apt:
		  sources:
			- ubuntu-toolchain-r-test
			  packages:
				- g++-5
	  env:
			 - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
git:
  depth: 3

branches:
  only:
    - master

before_install:
  - sudo apt-get install pkg-config
  - sudo add-apt-repository ppa:dns/gnu -y
  - sudo apt-get update -q
  - sudo apt-get install --only-upgrade autoconf
  - wget https://github.com/downloads/chokkan/liblbfgs/liblbfgs-1.10.tar.gz
  - tar -xzf liblbfgs-1.10.tar.gz
  - cd liblbfgs-1.10/
  - ./configure
  - sudo make all install
  - cd ../
  - autoreconf --force --install
  - ./configure

install:
  - make
  - sudo make install

script: make check
